name: Unzip and Build APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Zip files ko open karke root location par lana
    - name: Unzip Source Code
      run: |
        unzip -o *.zip
        cd OPOLIVES-main || true
        unzip -o OPO_LIVE_Flutter_Starter.zip -d ../
        cd ..

    # Java 17 setup (@v4)
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # Flutter SDK setup
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Dependencies download
    - name: Install Dependencies
      run: flutter pub get

    # Final APK Compile
    - name: Build APK
      run: flutter build apk --release

    # Artifact Release File Generator (@v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: OpoLive-Release-APK
        path: build/app/outputs/flutter-apk/app-release.apk
